### ISSUE TITLE
Applying font to username in GameJoltLogin gets rid of the GJ username

### ISSUE THREAD

**Issue by ActualMandM** [TentaRJ/GameJolt-FNF-Integration#10]
For some reason, applying a font to the username FlxText will cause the Game Jolt username to disappear. Adding a border or changing the alignment works just fine.

![image](https://user-images.githubusercontent.com/15317421/139561945-1315ad28-8dfb-4f57-a464-80a6ffc5cfb2.png)
![image](https://user-images.githubusercontent.com/15317421/139561942-a324b647-bb64-4a01-8db3-c99e10f3a421.png)
![image](https://user-images.githubusercontent.com/15317421/139561946-a43d4e95-b250-4f64-8d7d-4a7b049db369.png)

<details>
  <summary><b>DDTO SPOILER</b></summary>
This makes less sense considering the Game Jolt username will appear just fine in other places.

![image](https://user-images.githubusercontent.com/15317421/139561963-0cc2a85a-39c1-4295-b646-98ec25548454.png)
</details>

**Comment by TentaRJ** [comment]
Odd. I'll look into it on the next revision. Thank you!

~~Good luck on your project btw, would love to see how it goes~~

**Comment by ActualMandM** [comment]
We've already implemented GameJolt as of v2.0.5, hahaha

**Comment by TentaRJ** [comment]
Oh my bad! I guess I don't keep my eyes on that many mods lmao. Thanks anyway :)

**Comment by TentaRJ** [comment]
So I know this is late but I want to just tell you what happened just for clarity.
So whenever you do `\n`, it breaks the rest of the line. Happened to me when I've been updating it for the past week.
I fixed it and made a global font variable to change all the text fonts all at once :)
New update soon :)
