### ISSUE TITLE
Cant build the game

### ISSUE THREAD

**Issue by MadGuyXD** [TentaRJ/GameJolt-FNF-Integration#14]
Ok, i make the code look like you say. And in Main.hx i add public static var gjToastManager:GJToastManager; and gjToastManager = new GJToastManager(); addChild(gjToastManager); and i build and it say source/Main.hx:36: characters 35-49 : Type not found : GJToastManager. How can i fix this?

**Comment by TentaRJ** [comment]
Did you add `public static var gjToastManager:GJToastManager;` inside of the Main class? Make sure that it is in the first line of the Main class.

Example:
```hx
class Main extends Sprite
{
	public static var gjToastManager:GJToastManager; // Mmm crispy toast
	var gameWidth:Int = 1280; // Width of the game in pixels (might be less / more in actual pixels depending on your zoom).
	var gameHeight:Int = 720; // Height of the game in pixels (might be less / more in actual pixels depending on your zoom).
// Other things below this
```

**Comment by MadGuyXD** [comment]
im alreay do this but still not working

Vào Th 6, 3 thg 12, 2021 vào lúc 04:27 Tenta ***@***.***>
đã viết:

**Comment by MrClogsworthYT** [comment]
did you add import GameJolt; at the top?
