### ISSUE TITLE
technically this can be used for other games than fnf

### ISSUE THREAD

**Issue by MrClogsworthYT** [TentaRJ/GameJolt-FNF-Integration#16]
^

**Comment by TentaRJ** [comment]
might make it its own separate thing, but right now it references files and assets to FNF

**Comment by MrClogsworthYT** [comment]
> might make it its own separate thing, but right now it references files and assets to FNF

i already made a fork for this so no need lmao

**Comment by TentaRJ** [comment]
> > might make it its own separate thing, but right now it references files and assets to FNF
> 
> i already made a fork for this so no need lmao

🤨 

It still references FNF things... but ok.

I'll make a separate one down the line dw.

**Comment by MrClogsworthYT** [comment]
> > > might make it its own separate thing, but right now it references files and assets to FNF
> > 
> > 
> > i already made a fork for this so no need lmao
> 
> 🤨
> 
> It still references FNF things... but ok.
> 
> I'll make a separate one down the line dw.

oh
