### ISSUE TITLE
One question, can the user win the same trophy twice? Or is gamejolt already in charge of that?

### ISSUE THREAD

**Issue by diegoloboner** [TentaRJ/GameJolt-FNF-Integration#2]
One question, can the user win the same trophy twice? Or is gamejolt already in charge of that?

Pls

**Comment by TentaRJ** [comment]
The user can only win the same trophy once. It basically marks a true value on that trophy for the user.

**Comment by diegoloboner** [comment]
I understand he asked for cmd or powershell windows whenever he arrived at the same week (I put a trophy that if you arrived that week he would give you a trophy) it always came out that he had won the trophy

**Comment by TentaRJ** [comment]
Perhaps give a conditional to see if the user is allowed to get the trophy
