### ISSUE TITLE
source/TitleState.hx:44: characters 1-12 : Unexpected GameJoltAPI

### ISSUE THREAD

**Issue by XS09-dev** [TentaRJ/GameJolt-FNF-Integration#26]
Won't compile because of this

**Comment by 0neShyGuy** [comment]
did you import gamjolt at the top?

**Comment by XS09-dev** [comment]
> did you import gamjolt at the top?

yes

**Comment by 0neShyGuy** [comment]
ok did you do the project xml stuff?

**Comment by XS09-dev** [comment]
> ok did you do the project xml stuff?

yes

**Comment by 0neShyGuy** [comment]
take a screenshot

**Comment by ChillTeensie** [comment]
add 
import GameJolt.GameJoltAPI;
near the top of titlestate

**Comment by XS09-dev** [comment]
I did.

**Comment by Chidubemmo** [comment]
Have you tried reinstalling tentools? I had the same problem
