### ISSUE TITLE
the game will not login despite having the right token and shit

### ISSUE THREAD

**Issue by TheRealJake12** [TentaRJ/GameJolt-FNF-Integration#29]
it just pops up the not signed in

**Comment by PabloelproxD210** [comment]
yes

**Comment by TentaRJ** [comment]
More info might be needed to help fix your issue. Have you tried making sure your token is imputed properly? It's case sensitive.

**Comment by TheRealJake12** [comment]
yeah my token is all lowercase. My name might be a problem as it has a _ but it works in Indie Cross so Idk

**Comment by TheRealJake12** [comment]
FlxGameJolt: Unable to access user name or token, and no user name or token was passed.
the specific error in the Debug Log

**Comment by TheRealJake12** [comment]
> > FlxGameJolt: Unable to access user name or token, and no user name or token was passed. the specific error in the Debug Log
> 
> That's odd. Perhaps could you record/send a video so I could get some more info? I'll look into this problem.

aight 1 min

**Comment by TheRealJake12** [comment]
https://user-images.githubusercontent.com/84357907/162842689-54d29dfe-6122-4861-a6b8-d51a90b34cfc.mov


https://user-images.githubusercontent.com/84357907/162842699-625b9469-d6f7-4969-93cf-bed40ce6551e.mov

**Comment by TheRealJake12** [comment]
ok so little update, I saw the pr (which you should pull) and I fixed some shit but the error still occurs

**Comment by TentaRJ** [comment]
> 2022-04-11.17-16-56.mov 
>  2022-04-11.17-17-29.mov

sorry for the late reply, but can i see the terminal log from it? you can do it by doing `lime test windows`!

**Comment by TheRealJake12** [comment]
```
[TRACE] (GameJoltOption/press#2232): CS:GO get some bitches
0:15.06 [TRACE] (GameJoltLogin/create#418): false
0:23.42 [TRACE] (GameJoltLogin/create#499): lol
0:23.42 [TRACE] (GameJoltLogin/create#500): lol
0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#703): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol]()
0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#712): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol&signature=ce18aecd540b7a2091844655d7b4ad4a]()
0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#740): [success:"false",
message:"The signature you entered for the request is invalid.",
]
0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#762): { message => The signature you entered for the request is invalid., success => false }
0:23.68 [TRACE] (GameJoltAPI/authDaUser#155): user: myshitlol
0:23.68 [TRACE] (GameJoltAPI/authDaUser#156): token:myshitlol
0:23.68 [TRACE] (GameJoltAPI/authDaUser#180): User login failure!
0:23.68 [TRACE] (GameJoltLogin/create#418): false
```
I replaced my user and token with lol btw

**Comment by TentaRJ** [comment]
> 2022-04-11.17-16-56.mov 
>  2022-04-11.17-17-29.mov



> ```
> [TRACE] (GameJoltOption/press#2232): CS:GO get some bitches
> 0:15.06 [TRACE] (GameJoltLogin/create#418): false
> 0:23.42 [TRACE] (GameJoltLogin/create#499): lol
> 0:23.42 [TRACE] (GameJoltLogin/create#500): lol
> 0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#703): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol]()
> 0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#712): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol&signature=ce18aecd540b7a2091844655d7b4ad4a]()
> 0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#740): [success:"false",
> message:"The signature you entered for the request is invalid.",
> ]
> 0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#762): { message => The signature you entered for the request is invalid., success => false }
> 0:23.68 [TRACE] (GameJoltAPI/authDaUser#155): user: myshitlol
> 0:23.68 [TRACE] (GameJoltAPI/authDaUser#156): token:myshitlol
> 0:23.68 [TRACE] (GameJoltAPI/authDaUser#180): User login failure!
> 0:23.68 [TRACE] (GameJoltLogin/create#418): false
> ```
> 
> I replaced my user and token with lol btw

I kinda need to see the token and username to make sure its working with the html requests. You can always reset your game token in GameJolt btw. I think it may have to do with your game token probably having a `&` sign in it... but I'm not sure.

**Comment by TheRealJake12** [comment]
> > 2022-04-11.17-16-56.mov
> > 2022-04-11.17-17-29.mov
> 
> > ```
> > [TRACE] (GameJoltOption/press#2232): CS:GO get some bitches
> > 0:15.06 [TRACE] (GameJoltLogin/create#418): false
> > 0:23.42 [TRACE] (GameJoltLogin/create#499): lol
> > 0:23.42 [TRACE] (GameJoltLogin/create#500): lol
> > 0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#703): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol]()
> > 0:23.42 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#712): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=lol&user_token=lol&signature=ce18aecd540b7a2091844655d7b4ad4a]()
> > 0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#740): [success:"false",
> > message:"The signature you entered for the request is invalid.",
> > ]
> > 0:23.68 [TRACE] (tentools.api.FlxGameJolt/parseData#762): { message => The signature you entered for the request is invalid., success => false }
> > 0:23.68 [TRACE] (GameJoltAPI/authDaUser#155): user: myshitlol
> > 0:23.68 [TRACE] (GameJoltAPI/authDaUser#156): token:myshitlol
> > 0:23.68 [TRACE] (GameJoltAPI/authDaUser#180): User login failure!
> > 0:23.68 [TRACE] (GameJoltLogin/create#418): false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I replaced my user and token with lol btw
> 
> I kinda need to see the token and username to make sure its working with the html requests. You can always reset your game token in GameJolt btw. I think it may have to do with your game token probably having a `&` sign in it... but I'm not sure.

```
[TRACE] (GameJoltAPI/connect#135): Grabbing API keys...
0:17.20 [TRACE] (GameJoltOption/press#2232): CS:GO get some bitches
0:17.22 [TRACE] (GameJoltLogin/create#418): false
0:45.01 [TRACE] (GameJoltLogin/create#499): TheRealJake_12
0:45.01 [TRACE] (GameJoltLogin/create#500): loldontsteal
0:45.01 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#703): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=TheRealJake_12&user_token=loldontsteal]()
0:45.01 [TRACE] (tentools.api.FlxGameJolt/sendLoaderRequest#712): [https://gamejolt.com/api/game/v1/users/auth/?format=keypair&game_id=651622&username=TheRealJake_12&user_token=loldontsteal&signature=cc04915144d2706c6c92c6f2ed0776de]()
0:45.20 [TRACE] (tentools.api.FlxGameJolt/parseData#740): [success:"false",
message:"The signature you entered for the request is invalid.",
]
0:45.20 [TRACE] (tentools.api.FlxGameJolt/parseData#762): { message => The signature you entered for the request is invalid., success => false }
0:45.20 [TRACE] (GameJoltAPI/authDaUser#155): user: TheRealJake_12
0:45.20 [TRACE] (GameJoltAPI/authDaUser#156): token:loldontsteal
0:45.21 [TRACE] (GameJoltAPI/authDaUser#180): User login failure!
0:45.21 [TRACE] (GameJoltLogin/create#418): false
```

**Comment by TentaRJ** [comment]
That's odd, I'll look into it...

**Comment by TheRealJake12** [comment]
> That's odd, I'll look into it...

yo any news its been 2 weeks?

**Comment by TentaRJ** [comment]
> > That's odd, I'll look into it...
> 
> yo any news its been 2 weeks?

Haven't been able to replicate the problem on my end, so I haven't been able to tackle the problem.

**Comment by TheRealJake12** [comment]
gotcha I'll just wait for Indie Cross to release open source and steal code from that :)
