### ISSUE TITLE
bug :v

### ISSUE THREAD

**Issue by Jsa010** [TentaRJ/GameJolt-FNF-Integration#33]
![image](https://user-images.githubusercontent.com/98182734/164727459-0c5f3502-76c8-4f8f-9eb4-3a20097eb3ee.png)
and this is the code

![image](https://user-images.githubusercontent.com/98182734/164727554-f72a362a-4323-4cc8-9496-e08cdee1d95a.png)
![image](https://user-images.githubusercontent.com/98182734/164727668-29c75419-f973-4419-9639-67d066037a79.png)

**Comment by jasondingus** [comment]
i forgor to close this
