### ISSUE TITLE
wah

### ISSUE THREAD

**Issue by machonessiebaby** [TentaRJ/GameJolt-FNF-Integration#36]
![image](https://user-images.githubusercontent.com/56323671/164839007-673c9805-3030-4668-a729-1e9388e011a5.png)
i got this when openning the menu i had to remove the charbop due to errors i removed everything mentioning it

**Comment by Bacon69000** [comment]
add it again with this code:

charBop = new FlxSprite(FlxG.width - 400, 250);
charBop.frames = Paths.getSparrowAtlas('characters/BOYFRIEND');
charBop.animation.addByPrefix('idle', 'BF idle dance', 24, false);
charBop.animation.addByPrefix('loggedin', 'BF HEY', 24, false);
charBop.setGraphicSize(Std.int(charBop.width * 1.4));
charBop.antialiasing = true;
charBop.flipX = false;
add(charBop);

**Comment by machonessiebaby** [comment]
> add it again with this code:
> 
> charBop = new FlxSprite(FlxG.width - 400, 250); charBop.frames = Paths.getSparrowAtlas('characters/BOYFRIEND'); charBop.animation.addByPrefix('idle', 'BF idle dance', 24, false); charBop.animation.addByPrefix('loggedin', 'BF HEY', 24, false); charBop.setGraphicSize(Std.int(charBop.width * 1.4)); charBop.antialiasing = true; charBop.flipX = false; add(charBop);

forgot to say i fixed this i removed everything with charbop and it works i may readd later
