### ISSUE TITLE
make this a haxelib

### ISSUE THREAD

**Issue by Stilic** [TentaRJ/GameJolt-FNF-Integration#41]
this would simplify the install and update of shit

**Comment by Stilic** [comment]
i can do it myself also

**Comment by TentaRJ** [comment]
Why is this an issue and not a PR or its own fork?

Plus having it like this would allow people to literally just throw the file in and add a few lines. It is fine just being in the source folder of the mod.

**Comment by Stilic** [comment]
and what if i want to use that in a regular haxeflixel project? the best way to do that is to have this as a haxelib! (look at polybius hxcodec lib for example)
