### ISSUE TITLE
Psych Support When

### ISSUE THREAD

**Issue by Jsa010** [TentaRJ/GameJolt-FNF-Integration#42]
Pls Put A Psych Support Cus This have Like 100 Errors 

:(

**Comment by TentaRJ** [comment]
maybe

**Comment by Jsa010** [comment]
Yay

**Comment by LEON-BROTHER** [comment]
I got this to run with Psych

**Comment by TheRealJake12** [comment]
> Pls Put A Psych Support Cus This have Like 100 Errors
> 
> :(

1. Don't use Psych. Its not cool anymore. 2. what are the errors?

**Comment by Jsa010** [comment]
> > Pls Put A Psych Support Cus This have Like 100 Errors
> 
> > 
> 
> > :(
> 
> 
> 
> 1. Don't use Psych. Its not cool anymore. 2. what are the errors?

1.no,psych is easier
2.Something about public thing in main.hx + gamejolt files shit

**Comment by TheRealJake12** [comment]
1. Actually, With all of its modsupport and lua, Its a pain to use the source code.
2. just download the code and look at the examples

**Comment by Jsa010** [comment]
1.i like source and use it lol
2.tried + still not working

**Comment by TheRealJake12** [comment]
1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
2. Try looking at the pull requests and read the one about Psych Engine support

**Comment by Jsa010** [comment]
> 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
> 2. I have no idea how to fix try adding shit to ClientPrefs or something

1.kade is vanilla with options,input n accuracy
2.i think that's da problem

**Comment by SirScrubBunsDEV** [comment]
> 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)

Please elaborate. 
Psych is leading in simplicity, lua, character creation, and custom states. 
It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months. 

Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.

You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.

And since it isn't a fact, you shouldn't argue somebody else's opinion.
Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. 
Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?

You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.

I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.

**Comment by TheRealJake12** [comment]
> > 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
> 
> Please elaborate. Psych is leading in simplicity, lua, character creation, and custom states. It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months.
> 
> Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.
> 
> You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.
> 
> And since it isn't a fact, you shouldn't argue somebody else's opinion. Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?
> 
> You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.
> 
> I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.

1. u mad bro?
![TrollFace](https://user-images.githubusercontent.com/84357907/168234981-b4f47bd5-e481-4651-aa2c-ccdf24dabce1.png)
2. Custom States : Any engine can do custom states dumbass. Its HaxeFlixel.
3. Difficulty : Ok so what if its easy. Its being milked to death for that reason. It's main gimmick is the lua modsupport. Every engine is trying to copy that same gimmick because they saw that Psych blew up for it.
4. Other Mods : Indie Cross is on Kade 1.6.1. Hex is on KE 1.8. Yeah Shaggy is on Psych. 
5. Opinion : Uh no shit its not a fact. I just said I recommend using Kade or some shit. Even forever engine.

**Comment by Jsa010** [comment]
> > > 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
> > 
> > 
> > Please elaborate. Psych is leading in simplicity, lua, character creation, and custom states. It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months.
> > Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.
> > You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.
> > And since it isn't a fact, you shouldn't argue somebody else's opinion. Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?
> > You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.
> > I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.
> 
> 1. u mad bro?
>    ![TrollFace](https://user-images.githubusercontent.com/84357907/168234981-b4f47bd5-e481-4651-aa2c-ccdf24dabce1.png)
> 2. Custom States : Any engine can do custom states dumbass. Its HaxeFlixel.
> 3. Difficulty : Ok so what if its easy. Its being milked to death for that reason. It's main gimmick is the lua modsupport. Every engine is trying to copy that same gimmick because they saw that Psych blew up for it.
> 4. Other Mods : Indie Cross is on Kade 1.6.1. Hex is on KE 1.8. Yeah Shaggy is on Psych.
> 5. Opinion : Uh no shit its not a fact. I just said I recommend using Kade or some shit. Even forever engine.

imagine a log in system on lua
that will be no sense

**Comment by TheRealJake12** [comment]
> > > > 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
> > > 
> > > 
> > > Please elaborate. Psych is leading in simplicity, lua, character creation, and custom states. It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months.
> > > Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.
> > > You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.
> > > And since it isn't a fact, you shouldn't argue somebody else's opinion. Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?
> > > You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.
> > > I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.
> > 
> > 
> > 
> > 1. u mad bro?
> >    ![TrollFace](https://user-images.githubusercontent.com/84357907/168234981-b4f47bd5-e481-4651-aa2c-ccdf24dabce1.png)
> > 2. Custom States : Any engine can do custom states dumbass. Its HaxeFlixel.
> > 3. Difficulty : Ok so what if its easy. Its being milked to death for that reason. It's main gimmick is the lua modsupport. Every engine is trying to copy that same gimmick because they saw that Psych blew up for it.
> > 4. Other Mods : Indie Cross is on Kade 1.6.1. Hex is on KE 1.8. Yeah Shaggy is on Psych.
> > 5. Opinion : Uh no shit its not a fact. I just said I recommend using Kade or some shit. Even forever engine.
> 
> imagine a log in system on lua that will be no sense

1. It must be near impossible for it but I imagine this community will do it somehow.

**Comment by Jsa010** [comment]
nvm i fucking did it

**Comment by TheRealJake12** [comment]
cool good job

**Comment by Jsa010** [comment]
> cool good job

It took me 1 month

**Comment by SirScrubBunsDEV** [comment]
> > > 1. Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
> > 
> > 
> > Please elaborate. Psych is leading in simplicity, lua, character creation, and custom states. It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months.
> > Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.
> > You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.
> > And since it isn't a fact, you shouldn't argue somebody else's opinion. Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?
> > You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.
> > I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.
> 
> 1. u mad bro?
>    ![TrollFace](https://user-images.githubusercontent.com/84357907/168234981-b4f47bd5-e481-4651-aa2c-ccdf24dabce1.png)
> 2. Custom States : Any engine can do custom states dumbass. Its HaxeFlixel.
> 3. Difficulty : Ok so what if its easy. Its being milked to death for that reason. It's main gimmick is the lua modsupport. Every engine is trying to copy that same gimmick because they saw that Psych blew up for it.
> 4. Other Mods : Indie Cross is on Kade 1.6.1. Hex is on KE 1.8. Yeah Shaggy is on Psych.
> 5. Opinion : Uh no shit its not a fact. I just said I recommend using Kade or some shit. Even forever engine.

1: Yes, I did forget about hex, it's not on psych
2: Indie cross is confirmed to switch to psych for v2
3: You claim that Psych shouldn't be used because it's being milked, but so what? It allows more less experienced people to enter the FNF modding community, and you claim that just because so many people like it, that it shouldn't be used.

I think you're just salty, personally. 

It doesn't matter what engine anyone uses, but you seem to have a problem with Psych because so many people use it? So what? If other engines are copying lua gimmicks, GREAT! More people can softcode and coding is easier! I seriously don't get why you see any of these things as being bad

**Comment by Jsa010** [comment]
> Psych is unorganized and I recommend using Kade 1.5.4 or 1.6 (or 1.8 if you are smart)
Please elaborate. Psych is leading in simplicity, lua, character creation, and custom states. It is, without a doubt, the easiest engine I've ever used, and I used Kade for 6 whole months.
Within weeks of working with Psych, I was able to create pristine custom menus that I could only DREAM of beforehand.
You're taking your opinion (Psych is unorganized) and passing it off as a fact, when it really isn't.
And since it isn't a fact, you shouldn't argue somebody else's opinion. Without even having to BRING UP MY opinion, I could tell you that psych is easily the most simplistic and capable engine. Why do you think Indie Cross, Vs Freddy, Hex, Shaggy, Dsides, and all the others are switching to it?
You can't take your (rare) opinion and pass it off as fact, especially if there's so many that disagree.
I feel like the part of your replies where you said "Psych is not cool anymore" was completely asinine and didn't have to be there.
u mad bro?
Custom States : Any engine can do custom states dumbass. Its HaxeFlixel.
Difficulty : Ok so what if its easy. Its being milked to death for that reason. It's main gimmick is the lua modsupport. Every engine is trying to copy that same gimmick because they saw that Psych blew up for it.
Other Mods : Indie Cross is on Kade 1.6.1. Hex is on KE 1.8. Yeah Shaggy is on Psych.
Opinion : Uh no shit its not a fact. I just said I recommend using Kade or some shit. Even forever engine.
1: Yes, I did forget about hex, it's not on psych
2: Indie cross is confirmed to switch to psych for v2
3: You claim that Psych shouldn't be used because it's being milked, but so what? It allows more less experienced people to enter the FNF modding community, and you claim that just because so many people like it, that it shouldn't be used.
I think you're just salty, personally.
It doesn't matter what engine anyone uses, but you seem to have a problem with Psych because so many people use it? So what? If other engines are copying lua gimmicks, GREAT! More people can softcode and coding is easier! I seriously don't get why you see any of these things as being bad

you literally sayed about wanted a psych support

**Comment by Jsa010** [comment]
note for tenta:is solved,but is not appearing

**Comment by Chidubemmo** [comment]
> I got this to run with Psych

How
