### ISSUE TITLE
Too many arguments

### ISSUE THREAD

**Issue by ayoubslama123** [TentaRJ/GameJolt-FNF-Integration#44]
Plz Help I Get This Error Every Time :

source/GameJolt.hx:433: characters 76-81 : Too many arguments

**Comment by Jsa010** [comment]
Go to line 433

and replace the line code with this:
     `charBop.frames = Paths.getSparrowAtlas('characters/BOYFRIEND');`

**Comment by ayoubslama123** [comment]
Thanks
