### ISSUE TITLE
GameJoltLogin state

### ISSUE THREAD

**Issue by Gothbr4dn** [TentaRJ/GameJolt-FNF-Integration#56]
am I supposed to make one myself or is there one in the source code I can use

**Comment by TentaRJ** [comment]
`MusicBeatState.switchState(new GameJoltLogin);`

thats the default one I made

**Comment by jasondingus** [comment]
> `MusicBeatState.switchState(new GameJoltLogin);`
> 
> thats the default one I made

*MusicBeatState.switchState(new GameJoltLogin());
