### ISSUE TITLE
null object reference everytime I open the game

### ISSUE THREAD

**Issue by IdiotLimitedEdition** [TentaRJ/GameJolt-FNF-Integration#60]

**Comment by GamerPablito** [comment]
Chech #58 for more info

**Comment by IdiotLimitedEdition** [comment]
> Chech #58 for more info

It's different from my case the guy's game crashes when he tries to login mine instead when  I open it

**Comment by IdiotLimitedEdition** [comment]
Video

https://user-images.githubusercontent.com/111077202/210088917-36237f30-33bb-471d-a91d-228a803c4884.mp4

**Comment by RonyxDumb** [comment]
same problem damn

**Comment by RonyxDumb** [comment]
> > Chech #58 for more info
> 
> It's different from my case the guy's game crashes when he tries to login mine instead when I open it

I found the Solution!
Dont add the "GameJolt.connect();"and the GameJolt savestate user and token in the TittleState, because the game thinks you are already logged in, you have to do "FlxG.switchState(new GameJoltLoggin());" and the you can.

**Comment by RonyxDumb** [comment]
or consult the source codes of other mods that have used it, as in the case of Entity Breakout

**Comment by RonyxDumb** [comment]
in my profile, i created a fork where i was trying to solve some similar problem. If I'm not mistaken you should create ID AND Private KEY first.. then let me know

**Comment by IdiotLimitedEdition** [comment]
I checked other mods that i knew used the integration (pretty easy since most are made by bryghtfyre) but they all seems to have just copy pasted the to lines of code like I did, I have no idea if it's actually a Psych 0.6.3 thing or I'm just stupid (probably the latter)

**Comment by IdiotLimitedEdition** [comment]
btw this is what the command prompt says
```batchfile
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 642
Called from TitleState::create TitleState.hx line 100
Called from GameJoltAPI::connect GameJolt.hx line 72
Called from tentools.api.FlxGameJolt::init tentools/api/FlxGameJolt.hx line 212
Called from GameJoltAPI::connect GameJolt.hx line 74
Called from GJToastManager::createToast GameJolt.hx line 560
Called from Toast::new GameJolt.hx line 688
```

**Comment by IdiotLimitedEdition** [comment]
Then the game just decides to commit seppuku

**Comment by RonyxDumb** [comment]
I advise you to get the "GameJolt.hx" file from my fork(i fix stuff). Because the way it was programmed affected the game. Try using this method. . Let me know!

**Comment by IdiotLimitedEdition** [comment]
![image_2023-01-09_220101001](https://user-images.githubusercontent.com/111077202/211407516-0515f838-d87c-4315-9881-9f44c5213ee5.png)

**Comment by RonyxDumb** [comment]
No problem dude 👌
