### ISSUE TITLE
where can i find the private id for the game? 

### ISSUE THREAD

**Issue by RonyxDumb** [TentaRJ/GameJolt-FNF-Integration#61]
emhhh i read the guide how to setup gamejolt for fnf, but where can i find the private id of the game? will i be stupid or what

**Comment by GamerPablito** [comment]
First, you have to create a GameJolt page of your mod, and the obtain the priv key and the game key from it in the tab "Game API"

**Comment by GamerPablito** [comment]
It's not about the code, but the website of the mod you're creating

**Comment by RonyxDumb** [comment]
Ohhh thanks
