### ISSUE TITLE
source/GameJolt.hx:134: User login failure!

### ISSUE THREAD

**Issue by MadGuyXD** [TentaRJ/GameJolt-FNF-Integration#7]
Hey TentaRJ, i have seen the instructions and followed the instructions but why is it not working?

**Comment by TentaRJ** [comment]
Line 134 gets activated when the user isn't signed in.

You first need to authenticate your game with `GameJoltAPI.connect();` before you can do `GameJoltAPI.authDaUser(FlxG.save.data.gjUser, FlxG.save.data.gjToken);`.

Inside of the file is a template of the file you will need to make, that file being `GJKeys.hx`. Make sure you put your GameJolt Game's ID and API key in their respective variables.

**Comment by QuagFire101** [comment]
Huh I did exactly what you said and it still did not sign in. 
![image](https://user-images.githubusercontent.com/90576570/139763416-d9da4ee3-6a8f-40da-9b2b-a8efd1d8fdab.png)

**Comment by Jonnycatmeow** [comment]
mabey just delete the line of coding that has the line problem
